import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "About — Pet Past Life",
  description:
    "Learn how Pet Past Life uses AI to generate fun fictional past-life stories for your pet.",
};

export default function AboutPage() {
  return (
    <main className="page-wrap" style={{ alignItems: "flex-start", paddingTop: "4rem" }}>
      <div style={{ width: "100%", maxWidth: "42rem", margin: "0 auto" }}>
        <div className="card">
          <div className="card-header">
            <h1 className="title">Pet Past Life</h1>
            <p className="subtitle">Who was your pet before they were yours?</p>
          </div>

          <Section title="What It Does">
            Upload a photo of your cat, dog, rabbit — any pet — and we&apos;ll
            reveal the remarkable human they once were. Maybe a Victorian
            botanist. Maybe a Mongolian horse archer. The AI reads your pet&apos;s
            photo and conjures a fully fleshed-out past life complete with a
            name, era, location, life story, and echoes from their present
            appearance.
          </Section>

          <Section title="How It Works">
            Your photo is analyzed by <strong>Gemma 4 31B</strong>, Google&apos;s
            large multimodal AI model. The model looks at your pet&apos;s breed,
            posture, expression, and surroundings to craft a unique, vivid
            story. Every reading is one-of-a-kind.
          </Section>

          <Section title="Entertainment Only">
            Pet Past Life is a creative, playful experience — not a spiritual
            service. The stories are entirely fictional and generated by AI.
            Think of it as a fun character portrait for your pet.
          </Section>

          <Section title="Share Your Pet's Story">
            Once you get your reading, download it as an image and share it
            with friends. Each card includes a shareable quote and hashtags
            ready for social media.
          </Section>

          <Section title="Contact">
            Built with love for pet owners everywhere. Questions or feedback?{" "}
            <a href="mailto:rs21140@hanyang.ac.kr" style={{ color: "#6B1F2C" }}>
              rs21140@hanyang.ac.kr
            </a>
          </Section>
        </div>

        <p className="footer-note" style={{ marginTop: "1.5rem" }}>
          <a href="/" style={{ color: "rgba(255,255,255,0.6)" }}>
            ← Try it now
          </a>
        </p>
      </div>
    </main>
  );
}

function Section({
  title,
  children,
}: {
  title: string;
  children: React.ReactNode;
}) {
  return (
    <div style={{ marginBottom: "1.75rem" }}>
      <h2
        style={{
          fontSize: "0.65rem",
          letterSpacing: "0.2em",
          fontWeight: 600,
          textTransform: "uppercase",
          color: "#6B1F2C",
          marginBottom: "0.5rem",
          marginTop: 0,
        }}
      >
        {title}
      </h2>
      <div style={{ fontSize: "0.95rem", lineHeight: 1.7, color: "#374151" }}>
        {children}
      </div>
    </div>
  );
}
