import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Terms of Service — Pet Past Life",
};

export default function TermsPage() {
  return (
    <main className="page-wrap" style={{ alignItems: "flex-start", paddingTop: "4rem" }}>
      <div style={{ width: "100%", maxWidth: "42rem", margin: "0 auto" }}>
        <div className="card">
          <h1 className="title" style={{ fontSize: "2rem", marginBottom: "0.5rem" }}>
            Terms of Service
          </h1>
          <p style={{ fontSize: "0.8rem", color: "#9CA3AF", marginTop: 0, marginBottom: "2rem" }}>
            Last updated: May 2025
          </p>

          <Section title="Acceptance">
            By using Pet Past Life you agree to these Terms. If you do not
            agree, please do not use the Service.
          </Section>

          <Section title="Entertainment Only">
            All past-life stories generated by this Service are <strong>entirely
            fictional</strong> and created by an AI model. They are provided for
            entertainment purposes only and have no factual, scientific, or
            spiritual basis. Do not rely on them for any decision-making.
          </Section>

          <Section title="User Content">
            You retain ownership of any photos you upload. By submitting a
            photo you confirm that you have the right to share it and that it
            does not depict anything unlawful. You grant us a temporary,
            limited license to transmit the photo to our AI provider solely to
            generate your story.
          </Section>

          <Section title="Prohibited Use">
            You may not use the Service to:
            <ul>
              <li>Upload images that depict minors in any inappropriate context</li>
              <li>Attempt to reverse-engineer or scrape the Service</li>
              <li>Use automated tools to make bulk requests</li>
              <li>Violate any applicable law or regulation</li>
            </ul>
          </Section>

          <Section title="Disclaimer of Warranties">
            The Service is provided &ldquo;as is&rdquo; without warranty of any kind.
            We do not guarantee uptime, accuracy of generated content, or
            fitness for any particular purpose.
          </Section>

          <Section title="Limitation of Liability">
            To the fullest extent permitted by law, we shall not be liable for
            any indirect, incidental, or consequential damages arising from your
            use of the Service.
          </Section>

          <Section title="Changes">
            We may update these Terms at any time. Continued use of the Service
            after changes constitutes acceptance of the new Terms.
          </Section>

          <Section title="Contact">
            Questions?{" "}
            <a href="mailto:rs21140@hanyang.ac.kr" style={{ color: "#6B1F2C" }}>
              rs21140@hanyang.ac.kr
            </a>
          </Section>
        </div>

        <p className="footer-note" style={{ marginTop: "1.5rem" }}>
          <a href="/" style={{ color: "rgba(255,255,255,0.6)" }}>
            ← Back to Pet Past Life
          </a>
        </p>
      </div>
    </main>
  );
}

function Section({
  title,
  children,
}: {
  title: string;
  children: React.ReactNode;
}) {
  return (
    <div style={{ marginBottom: "1.75rem" }}>
      <h2
        style={{
          fontSize: "0.65rem",
          letterSpacing: "0.2em",
          fontWeight: 600,
          textTransform: "uppercase",
          color: "#6B1F2C",
          marginBottom: "0.5rem",
          marginTop: 0,
        }}
      >
        {title}
      </h2>
      <div style={{ fontSize: "0.95rem", lineHeight: 1.7, color: "#374151" }}>
        {children}
      </div>
    </div>
  );
}
